val

diff --git a/.github/workflows/integration.yml b/.github/workflows/integration.yml
--- a/.github/workflows/integration.yml
+++ b/.github/workflows/integration.yml
@@ -2,48 +2,47 @@ name: continous-integration
 
 on:
     push:
-          branches-ignore: [ga-ignore-*]
+        branches-ignore: [ga-ignore-*]
     pull_request:
-          branches-ignore: [ga-ignore-*]
+        branches-ignore: [ga-ignore-*]
 
 jobs:
-
     coding-style:
-      name: Run Banana
-      runs-on: ubuntu-lastet
-      container:
-          image: ghcr.io/epitech/coding-style-checker:lastet
-
-      steps:
-          - name: Chekout GH repo
-           uses: actions/checkout@v4
-
-          - name: Run coding-style checker
-           run: check.sh $(pwd) $(pwd)
-
-          - name: Report banana result
-           run: |
-              NB_ERROR=$(cat coding-style-reports.log | wc -l)
-              if [ $NB_ERROR -gt 0 ]; then 
-                ERROR=$(cat coding-style-reports.log)
-                echo "::error title=$NB_ERROR errors found::ERROR"
-                exit 1
-              fi
-              exit 0
-    
-    compile:
-        runs-on: ubuntu-lastet
+        name: Run Banana
+        runs-on: ubuntu-latest
+        container:
+            image: ghcr.io/epitech/coding-style-checker:latest
+        
         steps:
-          - name: Checkout GH repo
-           uses: action/checkout@v4
+            - name: Checkout GH repo
+              uses: actions/checkout@v4
 
-          - name: Compile repository
-           run: make
+            - name: Run coding-style-checker
+              run: check.sh $(pwd) $(pwd)
 
-          - name: Check binary presence
-           run: |
-            if [ ! -f ./swapupcase ]; then
-              echo "::error file=swapupcase, title=Binary not found Error::Binary not found"
-              exit 1
-            fi
-            exit 0
+            - name: Report banana result
+              run: |
+                NB_ERROR=$(cat coding-style-reports.log | wc -l)
+                if [ $NB_ERROR -gt 0 ]; then
+                    ERROR=$(cat coding-style-reports.log)
+                    echo "::error title=$NB_ERROR errors found::$ERROR"
+                    exit 1
+                fi
+                exit 0
+            
+    compile:
+        runs-on: ubuntu-latest
+        steps:
+            - name: Checkout GH repo
+              uses: actions/checkout@v4
+
+            - name: Compile repository
+              run: make
+
+            - name: Check binary presence
+              run: |
+                if [ ! -f ./swapupcase ]; then
+                    echo "::error file=swapupcase, title=Binary Error::Binary not found"
+                    exit 1
+                fi
+                exit 0
