bo

diff --git a/.github/workflows/integration.yml b/.github/workflows/integration.yml
--- a/.github/workflows/integration.yml
+++ b/.github/workflows/integration.yml
@@ -31,3 +31,20 @@ jobs:
                 exit 1
               fi
               exit 0
+    
+    compile :
+        runs-on: ubuntu-lastet
+        steps:
+          -name: Checkout GH repo
+           uses: action/checkout@v4
+
+          -name: Compile repository
+           run: make
+
+          -name: Check binary presence
+           run: |
+            if [ ! -f ./swapupcase ]; then
+              echo "::error file=swapupcase, title=Binary not found Error::Binary not found"
+              exit 1
+            fi
+            exit 0
